include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    todo: warning
    invalid_assignment: error
    missing_return: error

  language:
    strict-raw-types: false

linter:

  rules:
    - secure_pubspec_urls
    - package_names
    - void_checks
    - use_to_and_as_if_applicable
    - use_super_parameters
    - use_string_in_part_of_directives
    - use_string_buffers
    - use_rethrow_when_possible
    - use_raw_strings
    - use_named_constants
    - use_is_even_rather_than_modulo
    - use_if_null_to_convert_nulls_to_bools
    - use_function_type_syntax_for_parameters
    - use_full_hex_values_for_flutter_colors
    - use_enums
    - use_decorated_box
    - use_colored_box
    - unreachable_from_main
    - unnecessary_to_list_in_spreads
    - unnecessary_this
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_raw_strings
    - unnecessary_parenthesis
    - unnecessary_overrides
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_null_in_if_null_operators
    - unnecessary_null_checks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_aware_assignments
    - unnecessary_new
    - unnecessary_library_directive
    - unnecessary_late
    - unnecessary_getters_setters
    - unnecessary_constructor_name
    - unnecessary_const
    - unnecessary_brace_in_string_interps
    - unnecessary_await_in_return
    - unawaited_futures
    - type_init_formals
    - tighten_type_of_initializing_formals
    - sort_unnamed_constructors_first
    - sort_constructors_first
    - sort_child_properties_last
    - slash_for_doc_comments
    - sized_box_shrink_expand
    - sized_box_for_whitespace
    - require_trailing_commas
    - recursive_getters
    - provide_deprecation_message
    - prefer_typing_uninitialized_variables
    - prefer_spread_collections
    - prefer_null_aware_operators
    - prefer_null_aware_method_calls
    - prefer_mixin
    - prefer_is_not_operator
    - prefer_is_not_empty
    - prefer_is_empty
    - prefer_interpolation_to_compose_strings
    - prefer_int_literals
    - prefer_inlined_adds
    - prefer_initializing_formals
    - prefer_if_null_operators
    - prefer_if_elements_to_conditional_expressions
    - prefer_generic_function_type_aliases
    - prefer_function_declarations_over_variables
    - prefer_foreach
    - prefer_for_elements_to_map_fromIterable
    - prefer_final_in_for_each
    - prefer_final_fields
    - prefer_constructors_over_static_methods
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
    - prefer_const_constructors
    - prefer_conditional_assignment
    - prefer_collection_literals
    - prefer_asserts_with_message
    - prefer_asserts_in_initializer_lists
    - prefer_adjacent_string_concatenation
    - package_prefixed_library_names
    - package_api_docs
    - overridden_fields
    - only_throw_errors
    - one_member_abstracts
    - null_closures
    - null_check_on_nullable_type_parameter
    - noop_primitive_operations
    - non_constant_identifier_names
    - no_runtimeType_toString
    - no_leading_underscores_for_local_identifiers
    - no_leading_underscores_for_library_prefixes
    - no_default_cases
    - library_prefixes
    - library_names
    - library_annotations
    - leading_newlines_in_multiline_strings
    - implicit_call_tearoffs
    - implementation_imports
    - flutter_style_todos
    - file_names
    - exhaustive_cases
    - empty_constructor_bodies
    - empty_catches
    - do_not_use_environment
    - directives_ordering
    - deprecated_consistency
    - dangling_library_doc_comments
    - curly_braces_in_flow_control_structures
    - constant_identifier_names
    - conditional_uri_does_not_exist
    - combinators_ordering
    - camel_case_types
    - camel_case_extensions
    - await_only_futures
    - avoid_void_async
    - avoid_unused_constructor_parameters
    - avoid_unnecessary_containers
    - avoid_single_cascade_in_expression_statements
    - avoid_shadowing_type_parameters
    - avoid_setters_without_getters
    - avoid_returning_this
    - avoid_returning_null_for_void
    - avoid_return_types_on_setters
    - avoid_renaming_method_parameters
    - avoid_private_typedef_functions
    - avoid_positional_boolean_parameters
    - avoid_null_checks_in_equality_operators
    - avoid_js_rounded_ints
    - avoid_init_to_null
    - avoid_implementing_value_types
    - avoid_function_literals_in_foreach_calls
    - avoid_final_parameters
    - avoid_field_initializers_in_const_classes
    - avoid_escaping_inner_quotes
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_double_and_int_checks
    - avoid_catching_errors
    - avoid_bool_literals_in_conditional_expressions
    - annotate_overrides
    - avoid_types_on_closure_parameters
    - always_declare_return_types
    - valid_regexps
    - use_key_in_widget_constructors
    - unsafe_html
    - unrelated_type_equality_checks
    - unnecessary_statements
    - throw_in_finally
    - test_types_in_equals
    - prefer_void_to_null
    - no_logic_in_create_state
    - no_duplicate_case_values
    - no_adjacent_strings_in_list
    - literal_only_boolean_expressions
    - hash_and_equals
    - empty_statements
    - control_flow_in_finally
    - comment_references
    - collection_methods_unrelated_type
    - close_sinks
    - cancel_subscriptions
    - avoid_web_libraries_in_flutter
    - avoid_types_as_parameter_names
    - avoid_type_to_string
    - avoid_slow_async_io
    - avoid_relative_lib_imports
    - avoid_print
    - avoid_empty_else
    - always_use_package_imports


