name: hamzahllc
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  flutter_cache_manager: ^3.3.2
  connectivity_plus: ^6.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.0
  workmanager: ^0.5.2
  cached_network_image: ^3.3.1

  # Base utilities
  flutter_screenutil: ^5.9.0
  flutter_dotenv: ^5.1.0

  # Networking
  dio: ^5.4.0
  tf_dio_cache: ^1.0.2

  # Hardware & device interaction
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3

  # State management & dependency injection
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6


  # Custom widgets & UI enhancements
  cupertino_icons: ^1.0.6
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  intl: ^0.18.0
  photo_view: ^0.14.0
  go_router: ^13.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - .env.test
    - .env.prod


  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/almarai-regular.ttf
          weight: 400
        - asset: assets/fonts/almarai-bold.ttf
          weight: 700
        - asset: assets/fonts/almarai-extrabold.ttf
          weight: 800
